spring:
  application:
    name: mypayroll
  datasource:
    url: jdbc:postgresql://localhost:5432/sn_org
    username: snehasis
    password: *
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true
server:
  servlet:
    context-path: /mypayroll



